ASP.NET_CORE_Final_2019/ASP.NET_CORE_Final_2019/Controllers/ChaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASP.NET_CORE_Final_2019.Services;
using ASP.NET_CORE_Final_2019.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ASP.NET_CORE_Final_2019.Repository;

namespace ASP.NET_CORE_Final_2019.Controllers
{
    public class ChaController : Controller
    {
        public readonly IFSanpham _Sanpham;
        public readonly IFDonHang _Donhang;
        public ChaController(IFSanpham _IFSanpham, IFDonHang _IFDonhang)
        {
            _Sanpham = _IFSanpham;
            _Donhang = _IFDonhang;
        }

        public IActionResult Start()
        {
            Random rand = new Random();
            int sess = rand.Next(1, 9) * 100000 + rand.Next(0, 9) * 10000 + rand.Next(0, 9) * 1000 + rand.Next(0, 9) * 100 + rand.Next(0, 9) * 10 + rand.Next(0, 9);
            HttpContext.Session.SetInt32("Id", sess);
            
            // ADD DON HANG
            Donhang dh = new Donhang();
            dh.Id = HttpContext.Session.GetInt32("Id");
            DateTime now = DateTime.Now;
            dh.Ngay = now;
            dh.TrangThai = 0;
            dh.EmailKhachHang = "not";
            dh.PhuongThucThanhToan = "None";
            dh.Description = "null";
            _Donhang.addDonHang(dh);

            // ADD CHI TIET DON HANG
            Chitietdonhang ctdh = new Chitietdonhang(); ;
            IEnumerable<Sanpham> list = _Sanpham.GetSanPhams;
            List<Sanpham> listt = list.ToList();
            foreach (Sanpham l in listt)
            {
                ctdh.Id = HttpContext.Session.GetInt32("Id");
                ctdh.IdSanPham = l.Id;
                ctdh.SoLuong = 0;
                ctdh.Gia = 0;
                _Donhang.addChiTietDonHang(ctdh);
            }  

            //getSession();
            return RedirectToAction("Index", "Home", new { area = ""} );
        }

        public void getSession()
        {
            IEnumerable<Chitietdonhang> list = _Donhang.getChiTietDonHang(HttpContext.Session.GetInt32("Id"));
            int cnt = 0;
            foreach (Chitietdonhang l in list)
            {
                if (l.SoLuong > 0) cnt++;
            }
            ViewData["Count"] = cnt;
            ViewData["Session"] = HttpContext.Session.GetInt32("Id");
        }
    }
}

ASP.NET_CORE_Final_2019/ASP.NET_CORE_Final_2019/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASP.NET_CORE_Final_2019.Services;
using ASP.NET_CORE_Final_2019.Models;
using Microsoft.AspNetCore.Mvc;
using ASP.NET_CORE_Final_2019.Areas.Services;
using Microsoft.AspNetCore.Http;
using MimeKit;
using MailKit.Net.Smtp;
using System.Diagnostics;
using ASP.NET_CORE_Final_2019.PayPalHelper;
using Microsoft.Extensions.Configuration;
using PayPal.v1.Payments;
using System.Net.Http;
using System.IO;
using Newtonsoft.Json.Linq;
using ASP.NET_CORE_Final_2019.API_NganLuong;

namespace ASP.NET_CORE_Final_2019.Controllers
{
    public class CheckoutController : ChaController
    {
        public readonly IKhachHang _KhachHang;
        //public readonly IFDonHang _Donhang;
        public readonly IDonHang _DonhangAdmin;
        public IConfiguration _configuration { get; }
        public readonly string AuthyAPIKey;
        public CheckoutController(IFSanpham _IFSanpham, IFDonHang _IFDonhang, IKhachHang _IKhachHang, IConfiguration _Iconfiguration, IDonHang _IDonhang) : base(_IFSanpham, _IFDonhang)
        {
            _KhachHang = _IKhachHang;
            //_Donhang = _IFDonhang;
            _configuration = _Iconfiguration;
            _DonhangAdmin = _IDonhang;
            AuthyAPIKey = _configuration["API:AuthyAPIKey"];
        }

        [Route("Checkout")]
        [HttpGet]
        public IActionResult Checkout()
        {
            getSession();
            return View();
        }
        [Route("CheckCode")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CheckCode(CheckoutSum sum,String bankcode)
        {
            //test send SMS code
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Add("X-Authy-API-Key", AuthyAPIKey);

                var requestContent = new FormUrlEncodedContent(new[] {
                new KeyValuePair<string, string>("via", "sms"),
                new KeyValuePair<string, string>("phone_number", sum.khachhang.Sdt.ToString()),
                new KeyValuePair<string, string>("locale", "vi"),
                new KeyValuePair<string, string>("code_length", "6"),
                new KeyValuePair<string, string>("country_code", "84"),
            });

                HttpResponseMessage response = client.PostAsync(
                    "https://api.authy.com/protected/json/phones/verification/start",
                    requestContent).Result;

                HttpContent responseContent = response.Content;
                Console.WriteLine(responseContent.ReadAsStringAsync().Result);
            }
            ViewBag.bankcode = bankcode;
            return View(sum);
        }

        [Route("VerifyAndCheckout")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> VerifyAndCheckout(CheckoutSum sum, String code, String bankcode)
        {
            //---------------------- Mở ra khi  Hoàn Tất Hết
            var clientt = new HttpClient();

            // Add authentication header
            //clientt.DefaultRequestHeaders.Add("X-Authy-API-Key", AuthyAPIKey);

            //// https://api.authy.com/protected/json/phones/verification/check?phone_number=$USER_PHONE&country_code=$USER_COUNTRY&verification_code=$VERIFY_CODE
            //var api = "https://api.authy.com/protected/json/phones/verification/check?phone_number=" + sum.khachhang.Sdt + "&country_code=84&verification_code=" + code;
            //HttpResponseMessage response = await clientt.GetAsync(api);

            //// Get the response content.
            //HttpContent responseContent = response.Content;

            //// Get the stream of the content.
            //using (var reader = new StreamReader(await responseContent.ReadAsStreamAsync()))
            //{
            //    // Write the output.

            //    var result = await reader.ReadToEndAsync();
            //    // parse json string to array
            //    result = @"[" + result + "]";

            //    dynamic blogPosts = JArray.Parse(result);

            //    dynamic blogPost = blogPosts[0];
            //    string isTrue = blogPost.success;
            string isTrue = "True"; // dong lai khi hoan tat
                // -- End Mở ra
                if (isTrue == "True") // Code = Code : Success : True
                {
                    if (_KhachHang.GetKhachHang(sum.khachhang.Email) != null)
                    {
                        _KhachHang.UpdateKhachHang(sum.khachhang);
                    }
                    _KhachHang.AddKhachHang(sum.khachhang, HttpContext.Session.GetInt32("Id"));
                    _Donhang.UpdatePhuongThuc(HttpContext.Session.GetInt32("Id"), sum.PhuongThucThanhToan);
                    _Donhang.UpdateDescription(HttpContext.Session.GetInt32("Id"), "Chưa Thanh Toán");

                    if (sum.PhuongThucThanhToan == "Thanh Toán Khi Nhận Hàng")
                    {

                        try
                        {
                            var message = new MimeMessage();
                            message.From.Add(new MailboxAddress("Bá Khoa", "tbkhoa1999@gmail.com"));
                            message.To.Add(new MailboxAddress(sum.khachhang.Ten, sum.khachhang.Email));
                            message.Subject = "Thông báo cửa hàng Khoa Rau Củ: ";
                            message.Body = new TextPart("plain")
                            {
                                Text = " Bạn đã thanh toán thành công đơn hàng có mã: " + HttpContext.Session.GetInt32("Id") + "  |  Chúng tôi sẽ tiến hành kiểm tra và giao hàng đến bạn trong thời gian ngắn nhất. Cảm ơn bạn đã tin tưởng mua hàng ở Khoa Rau Củ. LOVE!!"
                            };
                            using (var client = new SmtpClient())
                            {
                                client.Connect("smtp.gmail.com", 587, false);
                                client.Authenticate("tbkhoa1999@gmail.com", "Iamonmyway1999@10101999");
                                client.Send(message);
                                client.Disconnect(true);
                            }
                            return View("../Checkout/Success");
                        }
                        catch (Exception ex)
                        {
                            ModelState.Clear();
                            ViewBag.Message = $" Oops! We have a problem here {ex.Message}";
                            Debug.WriteLine("Oops! We have a problem here" + ex.Message);
                            return RedirectToAction("Fail");
                        }
                    } // end thanh toan khi nhan hang
                    else if (sum.PhuongThucThanhToan == "PayPal")
                    {
                        Double summ = 0;
                        var PayPalAPI = new PayPalAPI(_configuration);
                        var itemList = new ItemList()
                        {
                            Items = new List<Item>()
                        };
                        IEnumerable<Chitietdonhang> a = _DonhangAdmin.GetChitietdonhang((int)HttpContext.Session.GetInt32("Id"));
                        foreach (var item in a)
                        {
                            Decimal soluong = 0;
                            string des = "";
                            Sanpham sp = _Sanpham.GetSanPham(item.IdSanPham);
                            if (sp.IdLoaiSanPham == 4)
                            {
                                soluong = (Decimal)item.SoLuong;
                                des = "unit: 1 cup";
                            }
                            else
                            {
                                soluong = (Decimal)item.SoLuong / 100;
                                des = "Unit: 100 gam";
                            }
                            itemList.Items.Add(new Item()
                            {
                                Name = sp.Ten,
                                Currency = "USD",
                                Price = Math.Round(((Decimal)item.Gia / 23000 / soluong), 2).ToString(),
                                Quantity = soluong.ToString(),
                                Description = des
                            });

                        }
                        foreach (var item in itemList.Items)
                        {
                            Debug.WriteLine(item.Name + " " + item.Quantity + " " + item.Price); // debug log
                            summ = summ + Math.Round((double.Parse(item.Price) * double.Parse(item.Quantity)), 2);
                        }
                        string URL = await PayPalAPI.getRedirectURLtoPayPal(summ, "USD", itemList);
                        return Redirect(URL);
                     }
                    else if (sum.PhuongThucThanhToan == "Ví Ngân Lượng" || sum.PhuongThucThanhToan=="Thẻ VISA" || sum.PhuongThucThanhToan=="Thẻ ATM")
                    {
                        Double summ = 0;
                        string payment_method = "";
                        string str_bankcode = bankcode;
                        IEnumerable<Chitietdonhang> a = _DonhangAdmin.GetChitietdonhang((int)HttpContext.Session.GetInt32("Id"));
                        if(sum.PhuongThucThanhToan=="Ví Ngân Lượng")
                        {
                            payment_method = "nl";
                        }
                        else if(sum.PhuongThucThanhToan =="Thẻ VISA")
                        {
                            payment_method = "VISA";
                        }
                        else if(sum.PhuongThucThanhToan=="Thẻ ATM")
                        {
                            payment_method = "ATM_ONLINE";
                        }
                        else
                        {
                            payment_method = "ATM_ONLINE";

ASP.NET_CORE_Final_2019/ASP.NET_CORE_Final_2019/Views/Checkout/CheckCode.cshtml
@{
        Layout = "~/Views/Shared/_Layout.cshtml";
}
@model CheckoutSum
@{

    string sdt = "";
    string temp = Model.khachhang.Sdt + "";
    for(int i =0;i<temp.Length;i++)
    {
        if(i>1 && i < temp.Length - 2)
        {
            sdt += "*";
        }
        else
        {
            sdt += temp[i];
        }
    }

}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Verify Code</title>
</head>
<body>
    <h4>Nhập Mã Xác Thực Đã Được Gửi Qua @sdt</h4>
    <form asp-action="VerifyAndCheckout" method="post">
        <input name="code" type="text" />
        <input type="hidden" asp-for="khachhang.Sdt" value="@Model.khachhang.Sdt" />
        <input type="hidden" asp-for="khachhang.Ten" value="@Model.khachhang.Ten" />
        <input type="hidden" asp-for="khachhang.Email" value="@Model.khachhang.Email" />
        <input type="hidden" asp-for="khachhang.DiaChi" value="@Model.khachhang.DiaChi" />
        <input type="hidden" asp-for="PhuongThucThanhToan" value="@Model.PhuongThucThanhToan" />
        <input type="hidden" name="bankcode" value="@ViewBag.bankcode" />
        <button type="submit" class="btn-success">Xác Nhận</button>
    </form>
</body>
</html>

ASP.NET_CORE_Final_2019/ASP.NET_CORE_Final_2019/Views/Checkout/Fail.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="ftco-section ftco-cart">
    <div class="container">
        <div class="row">
            <div class="col-md-12 ftco-animate">
                <div class="cart-list">
                    <h2>Thanh Toán Thất Bại! Vui Lòng Thử Lại Sau Hoặc Liện Hệ Admin</h2>
                    <h4 style="text-decoration-color:orangered">@ViewBag.message</h4>
                    <p class="breadcrumbs"><span class="mr-2"><a href="/Home">Trờ Về Giỏ Hàng</a></span></p>
                </div>
            </div>
        </div>
    </div>
</section>
<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" /></svg></div>

ASP.NET_CORE_Final_2019/ASP.NET_CORE_Final_2019/Views/Checkout/Success.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="ftco-section ftco-cart">
    <div class="container">
        <div class="row">
            <div class="col-md-12 ftco-animate">
                <div class="cart-list">
                    <h2>Thanh Toán Thành Công!</h2>
                    <form asp-controller="Cha"
                          asp-action="Start" method="post">
                          <p class="breadcrumbs"><span class="mr-2"><button type="submit">Tiếp Tục Mua Sắm</button></span></p>
                    </form>
                   
                </div>
            </div>
        </div>
    </div>
</section>
<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" /></svg></div>